export const UPDATE_MATCH_REQUEST = "UPDATE_MATCH_REQUEST";
export const UPDATE_MATCH_SUCCESS = "UPDATE_MATCH_SUCCESS";
export const UPDATE_MATCH_FAIL = "UPDATE_MATCH_FAIL";

export const CREATE_MATCH_REQUEST = "CREATE_MATCH_REQUEST";
export const CREATE_MATCH_SUCCESS = "CREATE_MATCH_SUCCESS";
export const CREATE_MATCH_FAIL = "CREATE_MATCH_FAIL";

export const DELETE_MATCH_REQUEST = "DELETE_MATCH_REQUEST";
export const DELETE_MATCH_SUCCESS = "DELETE_MATCH_SUCCESS";
export const DELETE_MATCH_FAIL = "DELETE_MATCH_FAIL";

export const GET_MATCHES_REQUEST = "GET_MATCHES_REQUEST";
export const GET_MATCHES_SUCCESS = "GET_MATCHES_SUCCESS";
export const GET_MATCHES_FAIL = "GET_MATCHES_FAIL";
